plugins:
  delete_user_topics_enabled:
    default: true

  delete_user_topics_dry_run:
    default: false

  delete_posts_for_usernamee:
    default: "soup"

  delete_posts_in_single_batchs:
    default: 1000